# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: BridgeCommunications.AskClyde
PackageVersion: 1.0.258
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{DF0CC116-C65F-4B9E-8920-14DF05D59D1E}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.bridgeoc.com/dl/44/AskClyde-Setup-1.0.258.msi
  InstallerSha256: CE44ECEA3C1A0065307114E26228BC47653CEB4892A95ED5F122DE545977F528
  ProductCode: '{DF0CC116-C65F-4B9E-8920-14DF05D59D1E}'
ManifestType: installer
ManifestVersion: 1.9.0
