# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: BridgeCommunications.AskClyde
PackageVersion: 1.0.256
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{AA755ACE-D0D9-4CBB-9108-43AB3CF302EF}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.bridgeoc.com/dl/44/AskClyde-Setup-1.0.256.msi
  InstallerSha256: ED8AB329B19AD49B0F958BCFF14E885E9C84106D2BB0904AEB747A8D30338FBB
  ProductCode: '{AA755ACE-D0D9-4CBB-9108-43AB3CF302EF}'
ManifestType: installer
ManifestVersion: 1.9.0
