# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: BridgeCommunications.AskClyde
PackageVersion: 1.0.257
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{20CD1C8F-28CE-4E74-86A3-C9702794FF53}'
Installers:
- Architecture: x64
  InstallerUrl: https://www.bridgeoc.com/dl/44/AskClyde-Setup-1.0.257.msi
  InstallerSha256: DF39762E34D7FEDC274D142A7CE91E553946299A675D7A16F45A95C1AF9915FA
  ProductCode: '{20CD1C8F-28CE-4E74-86A3-C9702794FF53}'
ManifestType: installer
ManifestVersion: 1.9.0
